/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaterFiltrationRouteImport } from './routes/water-filtration'
import { Route as TileRouteImport } from './routes/tile'
import { Route as TermsOfUseRouteImport } from './routes/terms-of-use'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as KitchenRouteImport } from './routes/kitchen'
import { Route as HandymanRouteImport } from './routes/handyman'
import { Route as FullRemodelRouteImport } from './routes/full-remodel'
import { Route as FlooringRouteImport } from './routes/flooring'
import { Route as ContractorsRouteImport } from './routes/contractors'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BathroomRouteImport } from './routes/bathroom'
import { Route as AccentWallRouteImport } from './routes/accent-wall'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'

const WaterFiltrationRoute = WaterFiltrationRouteImport.update({
  id: '/water-filtration',
  path: '/water-filtration',
  getParentRoute: () => rootRouteImport,
} as any)
const TileRoute = TileRouteImport.update({
  id: '/tile',
  path: '/tile',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfUseRoute = TermsOfUseRouteImport.update({
  id: '/terms-of-use',
  path: '/terms-of-use',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenRoute = KitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const HandymanRoute = HandymanRouteImport.update({
  id: '/handyman',
  path: '/handyman',
  getParentRoute: () => rootRouteImport,
} as any)
const FullRemodelRoute = FullRemodelRouteImport.update({
  id: '/full-remodel',
  path: '/full-remodel',
  getParentRoute: () => rootRouteImport,
} as any)
const FlooringRoute = FlooringRouteImport.update({
  id: '/flooring',
  path: '/flooring',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractorsRoute = ContractorsRouteImport.update({
  id: '/contractors',
  path: '/contractors',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BathroomRoute = BathroomRouteImport.update({
  id: '/bathroom',
  path: '/bathroom',
  getParentRoute: () => rootRouteImport,
} as any)
const AccentWallRoute = AccentWallRouteImport.update({
  id: '/accent-wall',
  path: '/accent-wall',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accent-wall': typeof AccentWallRoute
  '/bathroom': typeof BathroomRoute
  '/contact': typeof ContactRoute
  '/contractors': typeof ContractorsRoute
  '/flooring': typeof FlooringRoute
  '/full-remodel': typeof FullRemodelRoute
  '/handyman': typeof HandymanRoute
  '/kitchen': typeof KitchenRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/tile': typeof TileRoute
  '/water-filtration': typeof WaterFiltrationRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accent-wall': typeof AccentWallRoute
  '/bathroom': typeof BathroomRoute
  '/contact': typeof ContactRoute
  '/contractors': typeof ContractorsRoute
  '/flooring': typeof FlooringRoute
  '/full-remodel': typeof FullRemodelRoute
  '/handyman': typeof HandymanRoute
  '/kitchen': typeof KitchenRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/tile': typeof TileRoute
  '/water-filtration': typeof WaterFiltrationRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accent-wall': typeof AccentWallRoute
  '/bathroom': typeof BathroomRoute
  '/contact': typeof ContactRoute
  '/contractors': typeof ContractorsRoute
  '/flooring': typeof FlooringRoute
  '/full-remodel': typeof FullRemodelRoute
  '/handyman': typeof HandymanRoute
  '/kitchen': typeof KitchenRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/tile': typeof TileRoute
  '/water-filtration': typeof WaterFiltrationRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accent-wall'
    | '/bathroom'
    | '/contact'
    | '/contractors'
    | '/flooring'
    | '/full-remodel'
    | '/handyman'
    | '/kitchen'
    | '/privacy-policy'
    | '/projects'
    | '/services'
    | '/terms-of-use'
    | '/tile'
    | '/water-filtration'
    | '/admin/dashboard'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accent-wall'
    | '/bathroom'
    | '/contact'
    | '/contractors'
    | '/flooring'
    | '/full-remodel'
    | '/handyman'
    | '/kitchen'
    | '/privacy-policy'
    | '/projects'
    | '/services'
    | '/terms-of-use'
    | '/tile'
    | '/water-filtration'
    | '/admin/dashboard'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/accent-wall'
    | '/bathroom'
    | '/contact'
    | '/contractors'
    | '/flooring'
    | '/full-remodel'
    | '/handyman'
    | '/kitchen'
    | '/privacy-policy'
    | '/projects'
    | '/services'
    | '/terms-of-use'
    | '/tile'
    | '/water-filtration'
    | '/admin/dashboard'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccentWallRoute: typeof AccentWallRoute
  BathroomRoute: typeof BathroomRoute
  ContactRoute: typeof ContactRoute
  ContractorsRoute: typeof ContractorsRoute
  FlooringRoute: typeof FlooringRoute
  FullRemodelRoute: typeof FullRemodelRoute
  HandymanRoute: typeof HandymanRoute
  KitchenRoute: typeof KitchenRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProjectsRoute: typeof ProjectsRoute
  ServicesRoute: typeof ServicesRoute
  TermsOfUseRoute: typeof TermsOfUseRoute
  TileRoute: typeof TileRoute
  WaterFiltrationRoute: typeof WaterFiltrationRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/water-filtration': {
      id: '/water-filtration'
      path: '/water-filtration'
      fullPath: '/water-filtration'
      preLoaderRoute: typeof WaterFiltrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tile': {
      id: '/tile'
      path: '/tile'
      fullPath: '/tile'
      preLoaderRoute: typeof TileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-use': {
      id: '/terms-of-use'
      path: '/terms-of-use'
      fullPath: '/terms-of-use'
      preLoaderRoute: typeof TermsOfUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen': {
      id: '/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handyman': {
      id: '/handyman'
      path: '/handyman'
      fullPath: '/handyman'
      preLoaderRoute: typeof HandymanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/full-remodel': {
      id: '/full-remodel'
      path: '/full-remodel'
      fullPath: '/full-remodel'
      preLoaderRoute: typeof FullRemodelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flooring': {
      id: '/flooring'
      path: '/flooring'
      fullPath: '/flooring'
      preLoaderRoute: typeof FlooringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractors': {
      id: '/contractors'
      path: '/contractors'
      fullPath: '/contractors'
      preLoaderRoute: typeof ContractorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bathroom': {
      id: '/bathroom'
      path: '/bathroom'
      fullPath: '/bathroom'
      preLoaderRoute: typeof BathroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accent-wall': {
      id: '/accent-wall'
      path: '/accent-wall'
      fullPath: '/accent-wall'
      preLoaderRoute: typeof AccentWallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccentWallRoute: AccentWallRoute,
  BathroomRoute: BathroomRoute,
  ContactRoute: ContactRoute,
  ContractorsRoute: ContractorsRoute,
  FlooringRoute: FlooringRoute,
  FullRemodelRoute: FullRemodelRoute,
  HandymanRoute: HandymanRoute,
  KitchenRoute: KitchenRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProjectsRoute: ProjectsRoute,
  ServicesRoute: ServicesRoute,
  TermsOfUseRoute: TermsOfUseRoute,
  TileRoute: TileRoute,
  WaterFiltrationRoute: WaterFiltrationRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
